# Generated by Django 4.0.2 on 2022-02-11 09:00

from django.db import migrations, models
import objects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to=objects.models.user_directory_path, verbose_name='Фото')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('json', models.JSONField(blank=True, default=dict, editable=False, verbose_name='json')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
